import Link from 'next/link';
import { ALL_PACKS, CORPUS_SIZE, SIGNAL_CATALOGUE } from '@annex/engine';
import { Logo } from '@/components/primitives';
import { ThemeToggle } from '@/components/theme-toggle';
export const dynamic = 'force-dynamic';
export default function Home() {
  return <>
    <header className="landing-nav"><Link href="/" aria-label="Annex home"><Logo size={24}/></Link><nav><a href="#how">How it works</a><a href="https://github.com/shi1720/LexHack" target="_blank" rel="noreferrer">Source code ↗</a><ThemeToggle/><Link href="/login" className="btn btn-primary">Try the demo →</Link></nav></header>
    <main id="main">
      <section className="hero-grid">
        <div className="hero-copy"><p className="eyebrow"><span className="live-dot"/> BUILT FOR ACCOUNTABLE AI</p><h1>Show the code.<br/><em>Back the claim.</em></h1><p className="hero-sub">Your AI policy says people can override a decision. Does the code agree?</p><p className="hero-detail">Annex connects AI governance obligations to the files and lines that support them. Find gaps, plan the fix, and give reviewers evidence they can check.</p><div className="hero-actions"><Link className="btn btn-primary" href="/login">Explore a real scan <span>↗</span></Link><a className="btn" href="#how">See how it works</a></div><p className="hero-note">No signup. No API key. Your own demo workspace.</p><div className="hero-facts"><div><strong>{CORPUS_SIZE}</strong><span>executable controls</span></div><div><strong>{ALL_PACKS.length}</strong><span>rule packs</span></div><div><strong>{SIGNAL_CATALOGUE.length}</strong><span>source detectors</span></div></div></div>
        <div className="evidence-hero" aria-label="Illustrative finding from the bundled HireFlow sample">
          <div className="evidence-top"><span className="code">ANNEX / EVIDENCE REVIEW</span><span className="badge badge-neutral">Bundled sample</span></div>
          <div className="evidence-body"><div className="flex justify-between items-center gap-3"><span className="eyebrow">HireFlow</span><span className="badge badge-bad">Prohibited practice detected</span></div><h2>A hiring signal<br/>that crosses a line.</h2><p>Emotion inference in a recruitment workflow</p><div className="law-block"><span className="eyebrow">01 / THE OBLIGATION</span><strong>EU AI Act · Article 5(1)(f)</strong><p>Emotion inference at work or in education is prohibited, subject to the medical and safety exceptions.</p></div><div className="source-block"><span className="eyebrow">02 / THE EVIDENCE</span><div className="code file-label">src/interview/signal.ts</div><pre><span>17</span> export async function<br/><span>  </span> <b>detectEmotion</b>(frames, transcript)<br/><span>  </span> {'{ /* source cited in the scan */ }'}</pre></div><div className="next-block"><span className="eyebrow">03 / THE NEXT STEP</span><p>Remove the inference path. Document the change. Re-scan the system.</p></div></div><div className="evidence-bottom"><span className="live-dot"/> Rule-based finding <span>File · Line · Hash</span></div>
        </div>
      </section>
      <section className="pack-strip" aria-label="Supported frameworks"><span className="eyebrow">ONE EVIDENCE WORKFLOW</span><span>EU AI Act</span><span>GDPR</span><span>NYC Local Law 144</span><span>Colorado ADMT</span><span>NIST AI RMF</span></section>
      <section id="how" className="landing-section"><div className="section-heading"><div><p className="eyebrow">FROM QUESTION TO EVIDENCE</p><h2>Less chasing documents.<br/>More understanding the system.</h2></div><p>Made for builders, founders and assessors who need to work from the same facts.</p></div><div className="workflow-grid">{[
        ['01','Inspect the source','Scan a bundled sample or a public GitHub repository. Annex identifies source patterns and maps relevant controls to the selected markets.','Source, not self-report'],
        ['02','Review the finding','Read the obligation beside the cited code. Separate missing evidence from partial implementation. Ask for a plain language explanation.','Every answer has context'],
        ['03','Act and verify','Download a technical dossier or remediation patch. Compare scans, inspect the signed ledger, and publish a summary without exposing code.','A reviewable path forward'],
      ].map(([n,t,d,tag])=><article className="workflow-card" key={n}><span className="step-number">{n}</span><h3>{t}</h3><p>{d}</p><span className="eyebrow">{tag}</span></article>)}</div></section>
      <section className="comparison-section"><div><p className="eyebrow">A DEMO WITH A BEFORE AND AFTER</p><h2>The fix should change<br/>more than the paperwork.</h2><p>Compare HireFlow with HireFlow v3. Follow the prohibited practice back to its source, then inspect the revised system, remaining gaps and scan history.</p><Link href="/login" className="btn btn-primary">Follow the evidence →</Link></div><div className="comparison-card"><div><span className="eyebrow">HIREFlow</span><span className="badge badge-bad">Prohibited</span><p>Emotion inference in hiring</p></div><div className="comparison-arrow">↓ <span>Implementation changes</span></div><div><span className="eyebrow">HIREFlow v3</span><span className="badge badge-warn">High risk</span><p>Prohibited path removed. Obligations remain.</p></div><p className="comparison-foot">A better scan is evidence of change, not a certificate of compliance.</p></div></section>
      <section className="landing-section trust-section"><div><p className="eyebrow">TRUST STARTS WITH CLEAR LIMITS</p><h2>Checkable findings.<br/>Human judgment.</h2><p>Static analysis finds evidence in code. It cannot prove that a control works in production, determine every legal exception, or replace a qualified assessment.</p><p>AI is optional and only explains an existing finding. It cannot edit the scanner’s verdict or the evidence ledger.</p></div><div className="trust-grid"><article><strong>Deterministic core</strong><p>Classification and scoring run without a model. Repeat the same scan inputs and rules to reproduce the evidence.</p></article><article><strong>Tamper-evident ledger</strong><p>Hash chains and signatures make edits detectable. A signature identifies a key; it does not prove legal compliance.</p></article><article><strong>Honest evaluation</strong><p>The 50-case in-house benchmark tests regressions. It is not a real-world accuracy guarantee.</p></article><article><strong>Clear data boundaries</strong><p>The public demo uses temporary, isolated workspaces. Use self-hosting for private code and durable storage.</p></article></div></section>
      <section className="last-cta"><p className="eyebrow">LEXHACK 2026 · AI SAFETY & GOVERNANCE</p><h2>A claim is a starting point.<br/><em>Evidence is the next step.</em></h2><Link className="btn btn-primary" href="/login">Open your demo workspace →</Link></section>
    </main><footer className="landing-footer"><Logo muted/><p>Built by Shivam Gupta. Technical evidence for human review.<br/>Not legal advice or a conformity assessment.</p><a href="https://github.com/shi1720/LexHack">Open source ↗</a></footer>
  </>;
}
