import type { EvaluationContext, Language } from '../types.js';

/** Which language the remediation snippets should be written in. */
export function primaryLanguage(ctx: EvaluationContext): 'typescript' | 'python' {
  const counts: Partial<Record<Language, number>> = {};
  for (const f of ctx.snapshot.files) {
    counts[f.lang] = (counts[f.lang] ?? 0) + 1;
  }
  const py = counts.python ?? 0;
  const ts = (counts.typescript ?? 0) + (counts.javascript ?? 0);
  return py > ts ? 'python' : 'typescript';
}

const HEADER_TS = `/**
 * Generated by Annex (https://github.com/shi1720/LexHack) ; review before merging.
 *
 * This file exists to satisfy a specific obligation under Regulation (EU)
 * 2024/1689. The citation is in the block comment above each export. Annex
 * re-reads this file on every scan: if it is deleted or bypassed, the control
 * regresses and the conformity dossier is marked stale.
 */
`;

const HEADER_PY = `"""
Generated by Annex (https://github.com/shi1720/LexHack) -- review before merging.

This module exists to satisfy a specific obligation under Regulation (EU)
2024/1689. The citation is in the docstring of each function. Annex re-reads
this file on every scan: if it is deleted or bypassed, the control regresses
and the conformity dossier is marked stale.
"""
`;

// ---------------------------------------------------------------------------
// Art. 12 / 19 ; inference audit log
// ---------------------------------------------------------------------------

export function auditLogModule(lang: 'typescript' | 'python'): string {
  if (lang === 'python') {
    return `${HEADER_PY}
import hashlib
import json
import logging
import os
import uuid
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from typing import Any, Optional

logger = logging.getLogger("ai.audit")

# Article 19(1): logs must be kept for a period appropriate to the intended
# purpose and of AT LEAST SIX MONTHS, unless Union or national law provides
# otherwise. 190 days gives a small margin over the statutory floor.
LOG_RETENTION_DAYS = int(os.getenv("AI_LOG_RETENTION_DAYS", "190"))

REDACTED_FIELDS = {"email", "phone", "ssn", "national_id", "date_of_birth", "address"}


@dataclass
class InferenceRecord:
    """One automatically generated log entry.

    EU AI Act Article 12(1): high-risk AI systems shall technically allow for
    the automatic recording of events (logs) over the lifetime of the system.
    Article 12(2): the logging shall enable the identification of situations
    that may result in a risk within the meaning of Article 79(1) or in a
    substantial modification, and facilitate post-market monitoring (Art. 72).
    """

    decision_id: str
    occurred_at: str
    model_id: str
    model_version: str
    prompt_version: Optional[str]
    input_digest: str
    output_digest: str
    outcome: Optional[str]
    confidence: Optional[float]
    human_reviewer_id: Optional[str]
    human_decision: Optional[str]
    subject_ref: Optional[str]
    latency_ms: Optional[int]
    metadata: dict[str, Any] = field(default_factory=dict)


def _digest(value: Any) -> str:
    """Hash rather than store raw inputs: GDPR data minimisation (Art. 5(1)(c))
    while preserving the ability to prove which input produced which output."""
    payload = json.dumps(value, sort_keys=True, default=str)
    return "sha256:" + hashlib.sha256(payload.encode("utf-8")).hexdigest()


def redact(payload: dict[str, Any]) -> dict[str, Any]:
    return {k: ("[redacted]" if k.lower() in REDACTED_FIELDS else v) for k, v in payload.items()}


def record_inference(
    *,
    model_id: str,
    model_version: str,
    inputs: Any,
    output: Any,
    outcome: Optional[str] = None,
    confidence: Optional[float] = None,
    subject_ref: Optional[str] = None,
    prompt_version: Optional[str] = None,
    human_reviewer_id: Optional[str] = None,
    human_decision: Optional[str] = None,
    latency_ms: Optional[int] = None,
    metadata: Optional[dict[str, Any]] = None,
) -> InferenceRecord:
    """Record one model decision. Call this on EVERY inference that can affect
    a person -- a log that covers only the happy path proves nothing."""
    record = InferenceRecord(
        decision_id=str(uuid.uuid4()),
        occurred_at=datetime.now(timezone.utc).isoformat(),
        model_id=model_id,
        model_version=model_version,
        prompt_version=prompt_version,
        input_digest=_digest(inputs),
        output_digest=_digest(output),
        outcome=outcome,
        confidence=confidence,
        human_reviewer_id=human_reviewer_id,
        human_decision=human_decision,
        subject_ref=subject_ref,
        latency_ms=latency_ms,
        metadata=redact(metadata or {}),
    )
    logger.info("ai.inference", extra={"ai_audit": asdict(record)})
    return record
`;
  }

  return `${HEADER_TS}
import { createHash, randomUUID } from 'node:crypto';

/**
 * Article 19(1): logs must be kept for a period appropriate to the intended
 * purpose and of AT LEAST SIX MONTHS, unless Union or national law provides
 * otherwise. 190 days gives a small margin over the statutory floor.
 */
export const LOG_RETENTION_DAYS = Number(process.env.AI_LOG_RETENTION_DAYS ?? 190);

const REDACTED_FIELDS = new Set([
  'email', 'phone', 'ssn', 'nationalId', 'national_id', 'dateOfBirth', 'date_of_birth', 'address',
]);

export interface InferenceRecord {
  decisionId: string;
  occurredAt: string;
  modelId: string;
  modelVersion: string;
  promptVersion?: string;
  inputDigest: string;
  outputDigest: string;
  outcome?: string;
  confidence?: number;
  humanReviewerId?: string;
  humanDecision?: 'accepted' | 'overridden' | 'pending';
  subjectRef?: string;
  latencyMs?: number;
  metadata?: Record<string, unknown>;
}

/**
 * Hash rather than store raw inputs: GDPR Art. 5(1)(c) data minimisation,
 * while preserving the ability to prove which input produced which output.
 */
function digest(value: unknown): string {
  return 'sha256:' + createHash('sha256').update(JSON.stringify(value ?? null)).digest('hex');
}

function redact(payload: Record<string, unknown>): Record<string, unknown> {
  return Object.fromEntries(
    Object.entries(payload).map(([k, v]) => [k, REDACTED_FIELDS.has(k) ? '[redacted]' : v]),
  );
}

/**
 * EU AI Act Article 12(1): high-risk AI systems shall technically allow for the
 * automatic recording of events (logs) over the lifetime of the system.
 * Article 12(2): logging shall enable identification of situations that may
 * result in an Article 79(1) risk or a substantial modification, and shall
 * facilitate post-market monitoring under Article 72.
 *
 * Call this on EVERY inference that can affect a person. A log that covers only
 * the happy path proves nothing to a market surveillance authority.
 */
export function recordInference(input: {
  modelId: string;
  modelVersion: string;
  inputs: unknown;
  output: unknown;
  outcome?: string;
  confidence?: number;
  subjectRef?: string;
  promptVersion?: string;
  humanReviewerId?: string;
  humanDecision?: 'accepted' | 'overridden' | 'pending';
  latencyMs?: number;
  metadata?: Record<string, unknown>;
}): InferenceRecord {
  const record: InferenceRecord = {
    decisionId: randomUUID(),
    occurredAt: new Date().toISOString(),
    modelId: input.modelId,
    modelVersion: input.modelVersion,
    promptVersion: input.promptVersion,
    inputDigest: digest(input.inputs),
    outputDigest: digest(input.output),
    outcome: input.outcome,
    confidence: input.confidence,
    humanReviewerId: input.humanReviewerId,
    humanDecision: input.humanDecision,
    subjectRef: input.subjectRef,
    latencyMs: input.latencyMs,
    metadata: redact(input.metadata ?? {}),
  };

  // Replace with your own sink (database table, log pipeline, object storage).
  // Whatever you choose must survive ${'`LOG_RETENTION_DAYS`'} and be queryable by
  // decisionId and subjectRef ; Article 21(2) requires you to hand these logs
  // to a competent authority on reasoned request.
  console.info(JSON.stringify({ event: 'ai.inference', ...record }));
  return record;
}
`;
}

// ---------------------------------------------------------------------------
// Art. 14 ; human oversight
// ---------------------------------------------------------------------------

export function humanOversightModule(lang: 'typescript' | 'python'): string {
  if (lang === 'python') {
    return `${HEADER_PY}
import os
from dataclasses import dataclass
from enum import Enum
from typing import Any, Callable, Optional

# Article 14(4)(b): the overseer must remain aware of automation bias. Confidence
# alone is never sufficient grounds to skip review for a consequential outcome.
REVIEW_CONFIDENCE_FLOOR = float(os.getenv("AI_REVIEW_CONFIDENCE_FLOOR", "0.85"))

# Article 14(4)(e): a 'stop button' or similar procedure allowing the system to
# be brought to a halt in a safe state.
AI_ENABLED = os.getenv("AI_ENABLED", "true").lower() != "false"


class OversightOutcome(str, Enum):
    AUTO_APPLIED = "auto_applied"
    PENDING_HUMAN_REVIEW = "pending_human_review"
    HALTED = "halted"


@dataclass
class OversightDecision:
    outcome: OversightOutcome
    reason: str
    requires_reviewer: bool
    explanation: str


def gate(
    *,
    is_adverse: bool,
    confidence: Optional[float],
    explanation: str,
    escalate: Callable[[str], Any],
) -> OversightDecision:
    """Article 14 human oversight gate.

    Article 14(1): high-risk AI systems shall be designed and developed,
    including with appropriate human-machine interface tools, in such a way that
    they can be effectively overseen by natural persons during the period in
    which they are in use.

    Article 14(4)(d): the overseer must be able to decide not to use the system
    or otherwise disregard, override or reverse its output.
    """
    if not AI_ENABLED:
        return OversightDecision(OversightOutcome.HALTED, "Stop control engaged (AI_ENABLED=false).", False, explanation)

    if is_adverse:
        escalate("adverse outcome requires human confirmation")
        return OversightDecision(
            OversightOutcome.PENDING_HUMAN_REVIEW,
            "Adverse outcomes are never applied automatically (Art. 14(4)(d)).",
            True,
            explanation,
        )

    if confidence is not None and confidence < REVIEW_CONFIDENCE_FLOOR:
        escalate("confidence below review floor")
        return OversightDecision(
            OversightOutcome.PENDING_HUMAN_REVIEW,
            f"Confidence {confidence:.2f} is below the {REVIEW_CONFIDENCE_FLOOR:.2f} review floor.",
            True,
            explanation,
        )

    return OversightDecision(OversightOutcome.AUTO_APPLIED, "Non-adverse, high-confidence outcome.", False, explanation)
`;
  }

  return `${HEADER_TS}
/**
 * Article 14(4)(b): the overseer must remain aware of automation bias ; the
 * tendency to over-rely on output. Confidence alone is never sufficient grounds
 * to skip review for a consequential outcome.
 */
export const REVIEW_CONFIDENCE_FLOOR = Number(process.env.AI_REVIEW_CONFIDENCE_FLOOR ?? 0.85);

/**
 * Article 14(4)(e): a 'stop button' or similar procedure allowing the system to
 * be brought to a halt in a safe state.
 */
export const AI_ENABLED = process.env.AI_ENABLED !== 'false';

export type OversightOutcome = 'auto_applied' | 'pending_human_review' | 'halted';

export interface OversightDecision {
  outcome: OversightOutcome;
  reason: string;
  requiresReviewer: boolean;
  explanation: string;
}

/**
 * Article 14 human oversight gate.
 *
 * Article 14(1): high-risk AI systems shall be designed and developed,
 * including with appropriate human-machine interface tools, in such a way that
 * they can be effectively overseen by natural persons during the period in
 * which the AI system is in use.
 *
 * Article 14(4)(d): the overseer must be able to decide not to use the system,
 * or otherwise disregard, override or reverse its output.
 */
export function gate(input: {
  isAdverse: boolean;
  confidence?: number;
  explanation: string;
  escalate: (reason: string) => void | Promise<void>;
}): OversightDecision {
  const { isAdverse, confidence, explanation, escalate } = input;

  if (!AI_ENABLED) {
    return {
      outcome: 'halted',
      reason: 'Stop control engaged (AI_ENABLED=false).',
      requiresReviewer: false,
      explanation,
    };
  }

  if (isAdverse) {
    void escalate('adverse outcome requires human confirmation');
    return {
      outcome: 'pending_human_review',
      reason: 'Adverse outcomes are never applied automatically (Art. 14(4)(d)).',
      requiresReviewer: true,
      explanation,
    };
  }

  if (typeof confidence === 'number' && confidence < REVIEW_CONFIDENCE_FLOOR) {
    void escalate('confidence below review floor');
    return {
      outcome: 'pending_human_review',
      reason: \`Confidence \${confidence.toFixed(2)} is below the \${REVIEW_CONFIDENCE_FLOOR.toFixed(2)} review floor.\`,
      requiresReviewer: true,
      explanation,
    };
  }

  return {
    outcome: 'auto_applied',
    reason: 'Non-adverse, high-confidence outcome.',
    requiresReviewer: false,
    explanation,
  };
}
`;
}

// ---------------------------------------------------------------------------
// Art. 50(1) ; AI interaction disclosure
// ---------------------------------------------------------------------------

export function disclosureModule(lang: 'typescript' | 'python'): string {
  if (lang === 'python') {
    return `${HEADER_PY}
# Article 50(1) (in force since 2 August 2026): providers shall ensure that AI
# systems intended to interact directly with natural persons are designed and
# developed in such a way that the natural persons concerned are informed that
# they are interacting with an AI system.
#
# Article 50(5): the information shall be provided in a clear and
# distinguishable manner AT THE LATEST AT THE TIME OF THE FIRST INTERACTION or
# exposure, and shall conform to the applicable accessibility requirements.

AI_DISCLOSURE_NOTICE = (
    "You are chatting with an AI assistant, not a human. "
    "It can make mistakes, so check anything important. "
    "Ask for a human at any time."
)

AI_DISCLOSURE_LOCALES = {
    "en": AI_DISCLOSURE_NOTICE,
    "de": (
        "Sie chatten mit einem KI-Assistenten, nicht mit einem Menschen. "
        "Er kann Fehler machen - pruefen Sie wichtige Angaben. "
        "Sie koennen jederzeit nach einem Menschen fragen."
    ),
    "fr": (
        "Vous discutez avec un assistant IA, et non avec une personne. "
        "Il peut se tromper : verifiez toute information importante. "
        "Vous pouvez demander un interlocuteur humain a tout moment."
    ),
}


def disclosure_for(locale: str = "en") -> str:
    return AI_DISCLOSURE_LOCALES.get(locale.split("-")[0], AI_DISCLOSURE_NOTICE)


def opening_message(locale: str = "en") -> dict:
    """Prepend this to every conversation BEFORE the first model turn."""
    return {"role": "system_notice", "kind": "ai_disclosure", "text": disclosure_for(locale)}
`;
  }

  return `${HEADER_TS}
/**
 * Article 50(1) (in force since 2 August 2026): providers shall ensure that AI
 * systems intended to interact directly with natural persons are designed and
 * developed in such a way that the natural persons concerned are informed that
 * they are interacting with an AI system.
 *
 * Article 50(5): the information shall be provided in a clear and
 * distinguishable manner AT THE LATEST AT THE TIME OF THE FIRST INTERACTION or
 * exposure, and shall conform to the applicable accessibility requirements.
 */

export const AI_DISCLOSURE_NOTICE =
  'You are chatting with an AI assistant, not a human. It can make mistakes, so check anything important. Ask for a human at any time.';

export const AI_DISCLOSURE_LOCALES: Record<string, string> = {
  en: AI_DISCLOSURE_NOTICE,
  de: 'Sie chatten mit einem KI-Assistenten, nicht mit einem Menschen. Er kann Fehler machen ; prüfen Sie wichtige Angaben. Sie können jederzeit nach einem Menschen fragen.',
  fr: "Vous discutez avec un assistant IA, et non avec une personne. Il peut se tromper : vérifiez toute information importante. Vous pouvez demander un interlocuteur humain à tout moment.",
};

export function disclosureFor(locale = 'en'): string {
  return AI_DISCLOSURE_LOCALES[locale.split('-')[0] ?? 'en'] ?? AI_DISCLOSURE_NOTICE;
}

/**
 * Render this above the message list, not inside it ; Article 50(5) requires it
 * to be "clear and distinguishable", which a message styled like every other
 * message is not. Keep it visible rather than dismissible on first load, and
 * give it role="status" so screen readers announce it.
 */
export function aiDisclosureBanner(locale = 'en'): string {
  return \`<div role="status" class="ai-disclosure" data-ai-disclosure="art50-1">\${disclosureFor(locale)}</div>\`;
}
`;
}

// ---------------------------------------------------------------------------
// Art. 50(2) ; machine-readable marking of synthetic content
// ---------------------------------------------------------------------------

export function contentMarkingModule(lang: 'typescript' | 'python'): string {
  if (lang === 'python') {
    return `${HEADER_PY}
import hashlib
import json
from datetime import datetime, timezone

# Article 50(2) (in force 2 August 2026; systems already on the market before
# that date have until 2 December 2026 under Article 111(4)): providers of AI
# systems generating synthetic audio, image, video or text content shall ensure
# that the outputs are marked in a MACHINE-READABLE format and detectable as
# artificially generated or manipulated.
#
# A visible "AI-generated" badge does NOT satisfy this on its own -- the marking
# must be machine readable. For images/video/audio, prefer C2PA Content
# Credentials. The manifest below is the minimum text-content equivalent.

MARKING_SPEC = "annex/synthetic-content-marking/v1"


def build_manifest(*, content: str, model_id: str, model_version: str, purpose: str) -> dict:
    return {
        "spec": MARKING_SPEC,
        "syntheticContent": True,
        "generator": {"modelId": model_id, "modelVersion": model_version},
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "purpose": purpose,
        "contentDigest": "sha256:" + hashlib.sha256(content.encode("utf-8")).hexdigest(),
        "legalBasis": "Regulation (EU) 2024/1689, Article 50(2)",
    }


def mark_text(content: str, **kwargs) -> dict:
    """Return the content alongside its machine-readable provenance manifest.
    Serve the manifest in an HTTP header, a sidecar field or embedded metadata --
    never only as visible prose."""
    return {"content": content, "provenance": build_manifest(content=content, **kwargs)}
`;
  }

  return `${HEADER_TS}
import { createHash } from 'node:crypto';

/**
 * Article 50(2) (in force 2 August 2026; systems already on the market before
 * that date have until 2 December 2026 under Article 111(4)): providers of AI
 * systems generating synthetic audio, image, video or text content shall ensure
 * that the outputs are marked in a MACHINE-READABLE format and detectable as
 * artificially generated or manipulated.
 *
 * A visible "AI-generated" badge does not satisfy this on its own ; the marking
 * must be machine readable. For images, video and audio prefer C2PA Content
 * Credentials. The manifest below is the minimum text-content equivalent.
 */
export const MARKING_SPEC = 'annex/synthetic-content-marking/v1';

export interface ProvenanceManifest {
  spec: string;
  syntheticContent: true;
  generator: { modelId: string; modelVersion: string };
  generatedAt: string;
  purpose: string;
  contentDigest: string;
  legalBasis: string;
}

export function buildManifest(input: {
  content: string;
  modelId: string;
  modelVersion: string;
  purpose: string;
}): ProvenanceManifest {
  return {
    spec: MARKING_SPEC,
    syntheticContent: true,
    generator: { modelId: input.modelId, modelVersion: input.modelVersion },
    generatedAt: new Date().toISOString(),
    purpose: input.purpose,
    contentDigest: 'sha256:' + createHash('sha256').update(input.content).digest('hex'),
    legalBasis: 'Regulation (EU) 2024/1689, Article 50(2)',
  };
}

/**
 * Serve the manifest in an HTTP header (\`X-Content-Provenance\`), a sidecar
 * field, or embedded metadata ; never only as visible prose.
 */
export function markText(input: {
  content: string;
  modelId: string;
  modelVersion: string;
  purpose: string;
}): { content: string; provenance: ProvenanceManifest } {
  return { content: input.content, provenance: buildManifest(input) };
}
`;
}
