import type { RemediationPlan } from '@annex/engine';

/**
 * Open the remediation pull request on GitHub.
 *
 * Uses the Git data API rather than the contents API so all of the files land
 * in a single commit: a reviewer sees one coherent change, not nine.
 *
 * The token needs only `contents:write` and `pull_requests:write` on the one
 * repository. Annex never force-pushes and never touches the default branch.
 */

export class PullRequestError extends Error {
  constructor(
    message: string,
    readonly hint?: string,
  ) {
    super(message);
    this.name = 'PullRequestError';
  }
}

interface GitHubOptions {
  owner: string;
  repo: string;
  token: string;
  fetchImpl?: typeof fetch;
}

async function api<T>(
  opts: GitHubOptions,
  path: string,
  init: RequestInit = {},
): Promise<T> {
  const doFetch = opts.fetchImpl ?? fetch;
  const res = await doFetch(`https://api.github.com/repos/${opts.owner}/${opts.repo}${path}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${opts.token}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'Content-Type': 'application/json',
      'User-Agent': 'annex-compliance-engine',
      ...(init.headers ?? {}),
    },
  });

  if (res.status === 401 || res.status === 403) {
    throw new PullRequestError(
      `GitHub rejected the token (HTTP ${res.status}).`,
      'The token needs contents:write and pull_requests:write on this repository.',
    );
  }
  if (!res.ok) {
    const body = await res.text().catch(() => '');
    throw new PullRequestError(
      `GitHub returned ${res.status} for ${path}.`,
      body.slice(0, 300) || undefined,
    );
  }
  return (await res.json()) as T;
}

export interface OpenedPullRequest {
  number: number;
  url: string;
  branch: string;
  files: number;
}

export async function openRemediationPullRequest(
  opts: GitHubOptions,
  plan: RemediationPlan,
): Promise<OpenedPullRequest> {
  // 1. Where are we branching from?
  const repo = await api<{ default_branch: string }>(opts, '');
  const baseRef = await api<{ object: { sha: string } }>(opts, `/git/ref/heads/${repo.default_branch}`);
  const baseSha = baseRef.object.sha;
  const baseCommit = await api<{ tree: { sha: string } }>(opts, `/git/commits/${baseSha}`);

  // 2. One blob per file.
  const blobs = await Promise.all(
    plan.files.map(async (file) => {
      const blob = await api<{ sha: string }>(opts, '/git/blobs', {
        method: 'POST',
        body: JSON.stringify({ content: file.contents, encoding: 'utf-8' }),
      });
      return { path: file.path, mode: '100644' as const, type: 'blob' as const, sha: blob.sha };
    }),
  );

  // 3. One tree, one commit.
  const tree = await api<{ sha: string }>(opts, '/git/trees', {
    method: 'POST',
    body: JSON.stringify({ base_tree: baseCommit.tree.sha, tree: blobs }),
  });

  const commit = await api<{ sha: string }>(opts, '/git/commits', {
    method: 'POST',
    body: JSON.stringify({
      message: `${plan.title}\n\nGenerated by Annex from a conformity scan. Every file is additive and was written only where absent.\n\nCloses: ${plan.closes.join(', ')}`,
      tree: tree.sha,
      parents: [baseSha],
    }),
  });

  // 4. A new branch, never the default one.
  await api(opts, '/git/refs', {
    method: 'POST',
    body: JSON.stringify({ ref: `refs/heads/${plan.branchName}`, sha: commit.sha }),
  }).catch((err: unknown) => {
    if (err instanceof PullRequestError && err.message.includes('422')) {
      throw new PullRequestError(
        `The branch ${plan.branchName} already exists.`,
        'Delete it, or re-scan to generate a branch name for the current commit.',
      );
    }
    throw err;
  });

  // 5. The pull request.
  const pr = await api<{ number: number; html_url: string }>(opts, '/pulls', {
    method: 'POST',
    body: JSON.stringify({
      title: plan.title,
      head: plan.branchName,
      base: repo.default_branch,
      body: plan.body,
      maintainer_can_modify: true,
    }),
  });

  return { number: pr.number, url: pr.html_url, branch: plan.branchName, files: plan.files.length };
}
