import { defineSignal, type CompiledSignal } from './define.js';

const DOCS = /\.(md|mdx|rst|txt|adoc)$/i;

/**
 * Control signals are the *positive* evidence: places where the code already
 * implements something the law asks for. These are what turn a control from
 * "missing" into "satisfied", with a file and line to point an auditor at.
 */
export const CONTROL_SIGNALS: CompiledSignal[] = [
  // --- Art. 14 human oversight ---------------------------------------------
  defineSignal({
    id: 'control.human.review',
    label: 'Human review step',
    category: 'control',
    description: 'A person reviews or approves model output before it takes effect.',
    keywords: ['human review', 'human_review', 'humanreview', 'manual review', 'manual_review', 'manualreview', 'reviewer', 'needs_review', 'needs review', 'pending_review', 'pending review', 'awaiting_approval', 'human_in_the_loop', 'human in the loop', 'oversight', 'approval'],
    patterns: [
      /\b(human|manual)[_\s-]?(review|approval|check|verification|in[_\s-]the[_\s-]loop|oversight)\b/i,
      /\b(requires?|needs|pending|awaiting)[_\s]?(review|approval|human)\b/i,
      /\b(reviewer|approver)[_\s]?(id|queue|assignment|required)\b/i,
      /\bstatus\s*[:=]\s*['"](pending_review|needs_review|awaiting_approval)['"]/i,
    ],
    maxEvidence: 8,
  }),
  defineSignal({
    id: 'control.override',
    label: 'Human override of model output',
    category: 'control',
    description: 'A person can reverse, discard or correct what the model decided ; Art. 14(4)(d)-(e).',
    keywords: ['override', 'overrid', 'overrule', 'reverse_decision', 'revert_decision', 'discard_output', 'disregard'],
    patterns: [
      /\b(override|overrule|overridden)[_\s]?(decision|output|result|score|recommendation|reason)?\b/i,
      /\b(reverse|revert|discard|disregard)[_\s]?(decision|output|recommendation)\b/i,
    ],
    maxEvidence: 8,
  }),
  defineSignal({
    id: 'control.appeal',
    label: 'Appeal / contest mechanism',
    category: 'control',
    description: 'The affected person can contest the outcome and reach a human ; Art. 86, GDPR Art. 22(3), Colorado 6-1-1703(4)(b).',
    keywords: ['appeal', 'contest', 'dispute', 'reconsider', 'grievance', 'accommodation'],
    patterns: [
      /\b(appeal|contest|dispute|grievance|reconsider\w*)[_\s]?(request|process|endpoint|route|flow|handler|button)?\b/i,
      /['"]\/(api\/)?(appeals?|disputes?|contest)\b/i,
    ],
    maxEvidence: 8,
  }),
  defineSignal({
    id: 'control.confidence.threshold',
    label: 'Confidence gating / abstention',
    category: 'control',
    description: 'Low-confidence outputs are withheld or escalated instead of acted on ; Art. 14(4)(b).',
    keywords: ['confidence', 'threshold', 'abstain', 'uncertain', 'low_confidence'],
    patterns: [
      /\b(confidence|certainty|probability)\s*[<>]=?\s*[\d.]+/i,
      /\b(CONFIDENCE_THRESHOLD|MIN_CONFIDENCE|confidence_threshold|abstain|escalat\w+_threshold)\b/i,
      /\blow[_\s]?confidence\b/i,
    ],
    maxEvidence: 6,
  }),
  defineSignal({
    id: 'control.killswitch',
    label: 'Stop button / kill switch',
    category: 'control',
    description: 'The system can be interrupted or halted by an operator ; Art. 14(4)(e).',
    keywords: ['kill_switch', 'killswitch', 'kill switch', 'circuit_breaker', 'circuitbreaker', 'circuit breaker', 'feature_flag', 'featureflag', 'feature flag', 'disable_ai', 'disable ai', 'emergency_stop', 'emergency stop', 'ai_enabled', 'stop control', 'launchdarkly'],
    patterns: [
      /\b(kill[_\s]?switch|circuit[_\s]?breaker|emergency[_\s]?(stop|shutdown)|panic[_\s]?button)\b/i,
      /\b(feature[_\s]?flag|launchdarkly|unleash|flagsmith)\b/i,
      /\b(AI_ENABLED|MODEL_ENABLED|DISABLE_AI|disable_model|enabled\s*[:=]\s*(false|process\.env))\b/,
    ],
    maxEvidence: 6,
  }),

  // --- Art. 12 / 19 record-keeping -----------------------------------------
  defineSignal({
    id: 'control.logging.inference',
    label: 'Inference logging',
    category: 'control',
    description: 'Model inputs, outputs and metadata are recorded ; Art. 12 automatic logging.',
    keywords: [
      'audit_log', 'auditlog', 'inference_log', 'model_log', 'prediction_log', 'log_inference',
      'langfuse', 'langsmith', 'helicone', 'decision', 'prediction',
    ],
    patterns: [
      /\b(audit|inference|model|prediction|decision|completion)[_\s]?log(s|ging|ger|_entry)?\b/i,
      /\blog[_\s]?(inference|prediction|decision|completion|request_and_response)\b/i,
      // Structured log call naming a decision-shaped event, e.g.
      //   log.info("credit_decision", application_id=..., model_version=...)
      /\b(log|logger|logging|log)\w*\.(info|warn|warning|error|debug|event)\s*\(\s*['"`][\w.:-]*(decision|inference|prediction|score|outcome|completion)/i,
      // Event-name string literal, which is how structured loggers are usually
      // called ; and the argument often sits on its own continuation line.
      /['"`][\w.:-]*_(decision|inference|prediction|score|outcome)['"`]/i,
      /['"`](decision|inference|prediction)[\w.:-]*['"`]\s*,/i,
      /\b(langfuse|langsmith|helicone|phoenix\.trace|openllmetry|traceloop)\b/i,
      /\b(insert|create|record|persist)\w*\([\s\S]{0,40}\b(audit|inference|prediction|decision)/i,
    ],
    maxEvidence: 10,
  }),
  defineSignal({
    id: 'control.logging.retention',
    label: 'Log retention policy',
    category: 'control',
    description: 'Logs are kept for a defined period ; Art. 19 requires at least six months.',
    keywords: ['retention', 'retain', 'ttl', 'expire_after', 'expires', 'archive_after', 'log_retention', 'retention_days', ' days'],
    patterns: [
      /\b(retention|retain)[_\s]?(period|days|months|policy|until)\b/i,
      /\b(RETENTION_DAYS|LOG_RETENTION|retention_days)\s*[:=]\s*\d+/i,
      /\b(expire[_\s]?after|ttl)\s*[:=]\s*[\d'"]/i,
    ],
    maxEvidence: 6,
  }),
  defineSignal({
    id: 'control.logging.structured',
    label: 'Structured logging / observability',
    category: 'control',
    description: 'Events are emitted in a machine-readable, queryable form.',
    keywords: ['pino', 'winston', 'structlog', 'opentelemetry', 'otel', 'datadog', 'sentry', 'logger.info'],
    patterns: [
      /\b(pino|winston|bunyan|structlog|loguru|zerolog|logrus)\b/,
      /\b(opentelemetry|otel|@sentry\/|datadog|dd-trace|newrelic)\b/i,
      /\blogger\.(info|warn|error|debug)\s*\(\s*\{/,
    ],
    maxEvidence: 6,
  }),
  defineSignal({
    id: 'control.traceability.id',
    label: 'Traceable request / decision identifier',
    category: 'control',
    description: 'Each decision carries an identifier that links it back to inputs and model version.',
    keywords: ['trace_id', 'traceid', 'request_id', 'requestid', 'correlation_id', 'correlationid', 'decision_id', 'decisionid', 'session_id', 'sessionid', 'run_id', 'runid'],
    patterns: [/\b(trace|request|correlation|decision|run|session)[_\s]?id\b/i],
    maxEvidence: 6,
  }),
  defineSignal({
    id: 'control.model.version',
    label: 'Model version pinning',
    category: 'control',
    description: 'The exact model version used for a decision is recorded ; Annex IV(2)(a) and Art. 12(2).',
    keywords: ['model_version', 'modelversion', 'model_id', 'modelid', 'model_name', 'modelname', 'model=', 'model:', 'model ', 'prompt_version', 'promptversion'],
    patterns: [
      /\bmodel[_\s]?(version|id|name|revision)\b/i,
      /\bmodel\s*[:=]\s*['"][\w.:@/-]+['"]/,
      /\bMODEL_VERSION\b|\bPROMPT_VERSION\b/,
    ],
    maxEvidence: 8,
  }),

  // --- Art. 50 transparency -------------------------------------------------
  defineSignal({
    id: 'transparency.ai-disclosure',
    label: 'AI interaction disclosure',
    category: 'transparency',
    description: 'Users are told they are interacting with an AI system ; Art. 50(1).',
    keywords: ['ai-generated', 'ai generated', 'ai_generated', 'generated by ai', 'powered by ai', 'you are chatting with', "you're chatting with", 'this is an ai', 'ai assistant', 'not a human', 'automated system', 'ai-disclosure', 'ai disclosure', 'ai_disclosure', 'aidisclosure', 'disclosure', 'disclaimer', 'ai notice', 'ai_notice'],
    patterns: [
      /(you('re| are) (chatting|speaking|interacting) with an? (ai|bot|automated)|this is an ai|not a (human|real person))/i,
      /\b(ai[_\s-]?(generated|disclosure|notice|disclaimer|banner|badge)|generated by ai|powered by ai)\b/i,
      /\b(AI_DISCLOSURE|AI_NOTICE|aiDisclosure|AiDisclaimer)\b/,
    ],
    scope: 'any',
    maxEvidence: 8,
  }),
  defineSignal({
    id: 'transparency.content.marking',
    label: 'Synthetic content marking',
    category: 'transparency',
    description: 'Generated content is marked machine-readably ; Art. 50(2) and 50(4).',
    keywords: ['c2pa', 'content credentials', 'content_credentials', 'watermark', 'synthid', 'provenance', 'contentauthenticity', 'content authenticity', 'xmp'],
    patterns: [
      /\b(c2pa|content[_\s]?credentials|content[_\s]?authenticity|synthid)\b/i,
      /\bwatermark\w*\b/i,
      /\b(provenance[_\s]?(metadata|manifest)|xmp[_\s]?metadata)\b/i,
    ],
    scope: 'any',
    maxEvidence: 6,
  }),
  defineSignal({
    id: 'transparency.explanation',
    label: 'Explanation of output',
    category: 'transparency',
    description: 'The system produces reasons for its outputs ; Art. 86 and Colorado 6-1-1703(4)(a).',
    keywords: ['explanation', 'explain', 'reason_code', 'reasoncode', 'reason code', 'shap', 'lime', 'feature_importance', 'feature importance', 'rationale', 'why_this', 'justification'],
    patterns: [
      /\b(explanation|rationale|reason(ing|_code|s_for)?|justification)\b\s*[:=]/i,
      /\b(shap|lime|feature[_\s]?importance|counterfactual|saliency)\b/i,
      /\b(explain\w*)\s*\(/i,
    ],
    maxEvidence: 8,
  }),
  defineSignal({
    id: 'transparency.instructions',
    label: 'Instructions for use / deployer documentation',
    category: 'transparency',
    description: 'Documentation aimed at whoever deploys the system ; Art. 13(2)-(3).',
    keywords: ['instructions for use', 'instructions_for_use', 'deployment guide', 'intended purpose', 'intended use', 'limitations', 'known issues', 'operator guide', 'out of scope'],
    patterns: [
      /\b(instructions?[_\s]for[_\s]use|intended[_\s](purpose|use)|operator[_\s]guide|deployment[_\s]guide)\b/i,
      /^#+\s*(limitations|intended use|out[- ]of[- ]scope|known issues)/im,
    ],
    paths: DOCS,
    scope: 'docs',
    maxEvidence: 6,
  }),
  defineSignal({
    id: 'transparency.model-card',
    label: 'Model card',
    category: 'transparency',
    description: 'A structured description of the model, its data and its limits ; Annex IV(2) and GPAI Annex XII.',
    keywords: ['model card', 'model_card', 'modelcard', 'system card'],
    patterns: [/\b(model|system)[_\s-]?card\b/i],
    scope: 'any',
    maxEvidence: 6,
  }),

  // --- Art. 10 data governance ---------------------------------------------
  defineSignal({
    id: 'data.pii.handling',
    label: 'Personal data processing',
    category: 'data',
    description: 'Personal data fields are read, stored or sent to a model.',
    keywords: ['email', 'phone', 'date_of_birth', 'dateofbirth', 'ssn', 'national_id', 'address', 'full_name', 'fullname', 'personal_data', 'pii', 'personally_identifiable'],
    patterns: [
      /\b(email|phone|date_of_birth|dob|ssn|social_security|national_id|passport|address|full_?name|first_?name|last_?name)\b\s*[:=?]/i,
      /\b(personal_data|pii|personally_identifiable)\b/i,
    ],
    excludePaths: /(^|\/)(test|tests|__tests__|spec)\//i,
    maxEvidence: 10,
  }),
  defineSignal({
    id: 'data.special-category',
    label: 'Special-category / protected attributes',
    category: 'data',
    description: 'Protected characteristics appear in the data model ; GDPR Art. 9 and Art. 10(5) AI Act.',
    keywords: ['ethnicity', 'race', 'religion', 'sexual_orientation', 'sexual orientation', 'disability', 'trade_union', 'trade union', 'political_opinion', 'political opinion', 'health_data', 'gender', 'nationality', 'protected attribute', 'protected class', 'eeo'],
    patterns: [
      /\b(ethnicity|race|religion|sexual[_\s]?orientation|disabilit\w+|trade[_\s]?union|political[_\s]?(opinion|affiliation)|genetic|biometric[_\s]?data)\b\s*[:=?]/i,
      /\b(protected[_\s]?(attribute|class|characteristic)s?)\b/i,
      /\b(gender|sex|age|nationality|marital_status)\b\s*[:=]\s*['"]?(string|str|text|enum)/i,
    ],
    maxEvidence: 8,
  }),
  defineSignal({
    id: 'data.bias.testing',
    label: 'Bias / fairness testing',
    category: 'data',
    description: 'Outputs are tested for disparate impact across groups ; Art. 10(2)(f)-(g), NYC LL 144, Colorado 6-1-1702.',
    keywords: ['fairness', 'bias', 'disparate', 'demographic_parity', 'equalized_odds', 'impact_ratio', 'selection_rate', 'four-fifths', 'aequitas', 'fairlearn'],
    patterns: [
      /\b(bias|fairness)[_\s]?(test|audit|metric|check|eval|report|assessment|mitigation)\w*\b/i,
      /\b(disparate[_\s]?impact|demographic[_\s]?parity|equal(ized)?[_\s]?odds|equal[_\s]?opportunity|impact[_\s]?ratio|selection[_\s]?rate|four[_\s-]?fifths)\b/i,
      /\b(fairlearn|aequitas|aif360|fairness_indicators|themis)\b/i,
    ],
    maxEvidence: 8,
  }),
  defineSignal({
    id: 'data.provenance',
    label: 'Dataset provenance / documentation',
    category: 'data',
    description: 'Where the training or reference data came from is documented ; Art. 10(2)(b)-(c), Annex IV(2)(d).',
    keywords: ['dataset', 'data source', 'datasheet', 'data card', 'provenance', 'lineage', 'training data', 'validation set'],
    patterns: [
      /\b(dataset|data)[_\s-]?(card|sheet|source|provenance|lineage|origin|licen[sc]e)\b/i,
      /\b(training|reference|evaluation|validation)[_\s]?data(\s?set)?\b/i,
      /^#+\s*(training data|data ?sources?|datasets?|data governance|provenance)/im,
    ],
    scope: 'any',
    maxEvidence: 8,
  }),
  defineSignal({
    id: 'data.consent',
    label: 'Consent capture',
    category: 'data',
    description: 'The system records a lawful basis or consent from the data subject.',
    keywords: ['consent', 'opt_in', 'optin', 'opt-in', 'lawful_basis', 'lawful basis', 'legal basis', 'legitimate interest', 'gdpr'],
    patterns: [
      /\b(consent)[_\s]?(given|granted|record|timestamp|version|required|withdrawn|banner)?\b/i,
      /\b(opt[_\s-]?in|lawful[_\s]?basis|legal[_\s]?basis|legitimate[_\s]?interest)\b/i,
    ],
    maxEvidence: 6,
  }),
  defineSignal({
    id: 'data.subject-rights',
    label: 'Data subject rights endpoints',
    category: 'data',
    description: 'Access, correction and erasure of personal data are implemented ; GDPR Arts. 15-17.',
    keywords: ['delete_account', 'delete account', 'right_to_erasure', 'right to erasure', 'erasure', 'data_export', 'export_my_data', 'data export', 'dsar', 'subject_access', 'subject access', 'rectification', 'right to be forgotten', 'data deletion', 'portability'],
    patterns: [
      /\b(dsar|subject[_\s]?access|right[_\s]?to[_\s]?(erasure|be[_\s]?forgotten|access|rectification)|data[_\s]?(export|portability|deletion))\b/i,
      /\b(delete|erase|purge|export)[_\s]?(user|account|customer|personal)[_\s]?data\b/i,
    ],
    maxEvidence: 6,
  }),

  // --- Art. 15 accuracy, robustness, cybersecurity -------------------------
  defineSignal({
    id: 'quality.eval.suite',
    label: 'Model evaluation suite',
    category: 'quality',
    description: 'Model behaviour is measured against a fixed set of cases ; Art. 15(1) accuracy metrics.',
    keywords: [
      'eval', 'benchmark', 'golden', 'ground_truth', 'groundtruth',
      'accuracy', 'precision', 'recall', 'f1', 'auc', 'threshold',
    ],
    patterns: [
      /\b(eval(uation)?s?|benchmark)[_\s]?(suite|set|dataset|harness|runner|case|script)\b/i,
      /\b(golden|ground[_\s]?truth|regression)[_\s]?(set|data|cases?|file)\b/i,
      /\b(roc_auc_score|precision_score|recall_score|f1_score|accuracy_score|classification_report|confusion_matrix)\b/,
      /\b(accuracy|precision|recall|f1[_\s]?score|auc|roc_auc|mae|rmse)\b\s*[:=(]/i,
      /\b(AUC|ACCURACY|PRECISION|RECALL)_THRESHOLD\b/,
      /\bdef\s+evaluate\b|\bfunction\s+evaluate\b/,
    ],
    maxEvidence: 8,
  }),
  defineSignal({
    id: 'quality.test.suite',
    label: 'Automated test suite',
    category: 'quality',
    description: 'The codebase has automated tests ; evidence of a quality management system under Art. 17.',
    keywords: ['describe(', 'it(', 'test(', 'def test_', 'assert', 'expect('],
    patterns: [
      /\b(describe|it|test)\s*\(\s*['"`]/,
      /^\s*def\s+test_\w+/m,
      /\bexpect\s*\(|\bassert\s+|\bassertEqual\b/,
    ],
    paths: /(^|\/)(tests?|__tests__|spec|e2e)\/|\.(test|spec)\.[tj]sx?$|^test_|_test\.(py|go)$/i,
    scope: 'code',
    maxEvidence: 6,
  }),
  defineSignal({
    id: 'quality.monitoring',
    label: 'Production monitoring / drift detection',
    category: 'quality',
    description: 'Live performance is observed after deployment ; Art. 72 post-market monitoring.',
    keywords: ['drift', 'monitor', 'metric', 'prometheus', 'grafana', 'alerting', 'alert', 'dashboard', 'evidently', 'whylabs', 'arize', 'post-market', 'post market'],
    patterns: [
      /\b(data|model|concept|prediction)[_\s]?drift\b/i,
      /\b(prometheus|grafana|evidently|whylabs|arize|alert(manager|ing)?)\b/i,
      /\b(monitor\w*|metric\w*)[_\s]?(model|prediction|inference|quality|performance)\b/i,
    ],
    maxEvidence: 6,
  }),
  defineSignal({
    id: 'security.prompt-injection',
    label: 'Prompt injection / jailbreak defence',
    category: 'security',
    description: 'Input is defended against adversarial manipulation ; Art. 15(5) cybersecurity.',
    keywords: ['prompt injection', 'prompt_injection', 'promptinjection', 'jailbreak', 'guardrail', 'sanitize', 'sanitise', 'moderation', 'llm_guard', 'rebuff', 'content_filter', 'content filter'],
    patterns: [
      /\b(prompt[_\s]?injection|jailbreak|guardrail|llm[_\s]?guard|rebuff|nemo[_\s]?guardrails)\b/i,
      /\b(sanitiz|escap|strip)\w*[_\s]?(input|prompt|user[_\s]?content)\b/i,
      /\bmoderations?\.(create|check)|\bcontent[_\s]?(filter|moderation)\b/i,
    ],
    maxEvidence: 6,
  }),
  defineSignal({
    id: 'security.redteam',
    label: 'Adversarial / red-team testing',
    category: 'security',
    description: 'The system is deliberately attacked before release ; Art. 15(5) and Art. 55(1)(b) for GPAI.',
    keywords: ['red team', 'red_team', 'redteam', 'adversarial', 'penetration test', 'pen test', 'pentest', 'attack_suite', 'injection_cases', 'jailbreak'],
    patterns: [/\b(red[_\s-]?team\w*|adversarial[_\s]?(test|example|robustness|suite)|pen[_\s]?test\w*)\b/i],
    scope: 'any',
    maxEvidence: 6,
  }),
  defineSignal({
    id: 'security.auth',
    label: 'Authentication / access control',
    category: 'security',
    description: 'Access to the system is restricted and attributable.',
    keywords: ['auth', 'session', 'jwt', 'rbac', 'permission', 'authorize', 'oauth'],
    patterns: [
      /\b(authenticat\w+|authoriz\w+|rbac|abac|permission[_\s]?check|access[_\s]?control)\b/i,
      /\b(jwt|oauth2?|session[_\s]?(cookie|token)|bearer[_\s]?token)\b/i,
    ],
    maxEvidence: 6,
  }),
  defineSignal({
    id: 'security.secrets.hardcoded',
    label: 'Hard-coded credential',
    category: 'security',
    description: 'A credential appears to be committed to the repository.',
    keywords: ['sk-', 'api_key =', 'apikey =', 'password =', 'secret =', 'ghp_'],
    patterns: [
      /['"](sk-[A-Za-z0-9_-]{20,}|ghp_[A-Za-z0-9]{30,}|AKIA[0-9A-Z]{16})['"]/,
      /\b(api[_-]?key|secret|password|token)\s*[:=]\s*['"][A-Za-z0-9_\-+/]{16,}['"]/i,
    ],
    excludePaths: /(^|\/)(test|tests|__tests__|spec|fixtures?|examples?)\/|\.(md|mdx|example|sample)$/i,
    scope: 'code',
    maxEvidence: 5,
  }),

  // --- Art. 9 / 17 / 72 / 73 governance ------------------------------------
  defineSignal({
    id: 'governance.risk-management',
    label: 'Risk management documentation',
    category: 'governance',
    description: 'A documented, iterative risk process exists ; Art. 9.',
    keywords: ['risk register', 'risk_register', 'risk assessment', 'risk management', 'risk matrix', 'threat model', 'mitigation', 'residual risk', 'risk-management'],
    patterns: [
      /\b(risk)[_\s-]?(register|assessment|management|analysis|matrix|log|treatment)\b/i,
      /\b(threat[_\s]?model|mitigation[_\s]?(plan|measure|strategy)|residual[_\s]?risk)\b/i,
    ],
    scope: 'any',
    maxEvidence: 8,
  }),
  defineSignal({
    id: 'governance.incident-response',
    label: 'Incident response process',
    category: 'governance',
    description: 'Serious malfunctions are detected, escalated and reported ; Art. 73.',
    keywords: ['incident', 'postmortem', 'post-mortem', 'on-call', 'oncall', 'runbook', 'escalation', 'escalate', 'sev1', 'pagerduty', 'opsgenie', 'market surveillance'],
    patterns: [
      /\b(incident)[_\s-]?(response|report|management|log|playbook|severity|channel)\b/i,
      /\b(post[_\s-]?mortem|runbook|escalation[_\s]?(path|policy|matrix)|on[_\s-]?call|pagerduty|opsgenie)\b/i,
      /\bsev[_-]?[012]\b/i,
    ],
    scope: 'any',
    maxEvidence: 8,
  }),
  defineSignal({
    id: 'governance.qms',
    label: 'Quality management system reference',
    category: 'governance',
    description: 'A recognised management system is referenced ; Art. 17, ISO/IEC 42001, ISO 9001, SOC 2.',
    keywords: ['iso 42001', 'iso/iec 42001', 'iso 9001', 'iso 27001', 'soc 2', 'soc2', 'nist ai rmf', 'ai rmf', 'quality management', 'quality_management'],
    patterns: [
      /\bISO[\s/]?(IEC[\s/]?)?(42001|23894|27001|9001)\b/i,
      /\bSOC[\s-]?2\b|\bNIST[\s]?AI[\s]?RMF\b|\bAI[\s]?RMF[\s]?1\.0\b/i,
      /\bquality[_\s]?management[_\s]?(system|policy)\b/i,
    ],
    scope: 'any',
    maxEvidence: 6,
  }),
  defineSignal({
    id: 'governance.dpia',
    label: 'Data protection / fundamental rights impact assessment',
    category: 'governance',
    description: 'A documented impact assessment exists ; GDPR Art. 35, AI Act Art. 27.',
    keywords: ['dpia', 'data protection impact', 'fria', 'fundamental rights impact', 'privacy impact', 'impact assessment'],
    patterns: [/\b(dpia|fria|data[_\s]?protection[_\s]?impact|fundamental[_\s]?rights[_\s]?impact|privacy[_\s]?impact[_\s]?assessment)\b/i],
    scope: 'any',
    maxEvidence: 6,
  }),
  defineSignal({
    id: 'governance.change-control',
    label: 'Change control',
    category: 'governance',
    description: 'Changes are reviewed and attributable ; Art. 17(1)(e) and Annex IV(2)(g).',
    keywords: ['codeowners', 'pull_request_template', 'branch protection', 'required_reviewers', 'changelog'],
    patterns: [/.*/],
    paths: /(^|\/)(CODEOWNERS|CHANGELOG(\.md)?|\.github\/(pull_request_template\.md|PULL_REQUEST_TEMPLATE\.md|CODEOWNERS))$/i,
    scope: 'any',
    maxEvidence: 4,
  }),
  defineSignal({
    id: 'governance.ci',
    label: 'Continuous integration pipeline',
    category: 'governance',
    description: 'Automated checks gate every change ; evidence for Art. 17 quality management.',
    keywords: ['jobs:', 'steps:', 'runs-on', 'pipeline', 'stages:'],
    patterns: [/\b(runs-on|jobs:|steps:|stages:|script:)\b/],
    paths: /(^|\/)(\.github\/workflows\/.*\.ya?ml|\.gitlab-ci\.yml|azure-pipelines\.yml|Jenkinsfile|\.circleci\/config\.yml)$/i,
    scope: 'any',
    maxEvidence: 4,
  }),
  defineSignal({
    id: 'governance.registration',
    label: 'EU database registration reference',
    category: 'governance',
    description: 'Registration in the EU database for high-risk systems ; Art. 49.',
    keywords: ['eu database', 'art. 49', 'article 49', 'ce marking', 'declaration of conformity', 'notified body'],
    patterns: [
      /\b(eu[_\s]?database|article[_\s]?49|art\.?[_\s]?49)\b/i,
      /\b(ce[_\s]?mark\w*|declaration[_\s]?of[_\s]?conformity|notified[_\s]?body|conformity[_\s]?assessment)\b/i,
    ],
    scope: 'any',
    maxEvidence: 6,
  }),
  defineSignal({
    id: 'governance.ai-act.reference',
    label: 'Explicit AI Act / AI governance reference',
    category: 'governance',
    description: 'The repository already reasons about AI regulation.',
    keywords: ['ai act', 'regulation (eu) 2024/1689', '2024/1689', 'annex iii', 'annex iv', 'gdpr', 'ai governance', 'article 5', 'article 14', 'article 50', 'art. 50', 'eu ai act'],
    patterns: [
      /\b(EU[\s]?AI[\s]?Act|Regulation\s*\(EU\)\s*2024\/1689|2024\/1689)\b/i,
      /\bAnnex\s+(III|IV|XI|XII)\b/,
      /\bai[_\s]?governance\b/i,
    ],
    scope: 'any',
    maxEvidence: 6,
  }),
];
