import { defineSignal, type CompiledSignal } from './define.js';

const NOT_DOCS = /\.(md|mdx|rst|txt)$/i;

/**
 * Signals that establish *that* the repository contains an AI system, and what
 * kind. These drive the Art. 3(1) "AI system" determination and the GPAI packs.
 */
export const AI_SIGNALS: CompiledSignal[] = [
  defineSignal({
    id: 'ai.provider.openai',
    label: 'OpenAI model provider',
    category: 'ai-usage',
    description: 'Calls an OpenAI-hosted model (GPT family, embeddings, moderation).',
    keywords: ['openai', 'gpt-', 'chatgpt'],
    patterns: [
      /\bfrom\s+openai\b|\brequire\(['"]openai['"]\)|\bimport\s+OpenAI\b|from\s+['"]openai['"]/,
      /\bopenai\.(chat|completions|responses|embeddings|images|audio|moderations)\b/i,
      /api\.openai\.com/i,
      /['"]gpt-(3\.5|4|4o|4\.1|5)[\w.-]*['"]/i,
      /\bOPENAI_API_KEY\b/,
    ],
    excludePaths: NOT_DOCS,
    maxEvidence: 6,
  }),
  defineSignal({
    id: 'ai.provider.anthropic',
    label: 'Anthropic model provider',
    category: 'ai-usage',
    description: 'Calls an Anthropic-hosted model (Claude family).',
    keywords: ['anthropic', 'claude'],
    patterns: [
      /\bfrom\s+anthropic\b|\brequire\(['"]@?anthropic[\w/-]*['"]\)|from\s+['"]@anthropic-ai\/[\w-]+['"]/,
      /\banthropic\.(messages|beta|completions)\b/i,
      /api\.anthropic\.com/i,
      /['"]claude-[\w.-]+['"]/i,
      /\bANTHROPIC_API_KEY\b/,
    ],
    excludePaths: NOT_DOCS,
    maxEvidence: 6,
  }),
  defineSignal({
    id: 'ai.provider.google',
    label: 'Google model provider',
    category: 'ai-usage',
    description: 'Calls a Google-hosted model (Gemini, Vertex AI, PaLM).',
    keywords: ['gemini', 'vertexai', 'vertex_ai', 'generativeai', 'googleai', 'palm'],
    patterns: [
      /google\.generativeai|@google\/gener(ative-ai|ai)|from\s+['"]@google-cloud\/vertexai['"]/i,
      /\bvertexai?\b.*\b(predict|generate|model)/i,
      /['"]gemini-[\w.-]+['"]/i,
      /\bGOOGLE_(API_KEY|GENAI_API_KEY)\b|\bGEMINI_API_KEY\b/,
    ],
    excludePaths: NOT_DOCS,
    maxEvidence: 6,
  }),
  defineSignal({
    id: 'ai.provider.cloud',
    label: 'Cloud inference platform',
    category: 'ai-usage',
    description: 'Uses a managed inference platform (Bedrock, Azure OpenAI, SageMaker, Replicate).',
    keywords: ['bedrock', 'sagemaker', 'azure.openai', 'azureopenai', 'replicate', 'together.ai', 'groq', 'fireworks.ai'],
    patterns: [
      /bedrock[-_]?(runtime|client)?|invoke_model|InvokeModelCommand/i,
      /sagemaker[-_]?runtime|invoke_endpoint/i,
      /AzureOpenAI|azure_endpoint|AZURE_OPENAI_/i,
      /replicate\.run|api\.replicate\.com/i,
      /api\.(groq|together|fireworks)\.(com|ai|xyz)/i,
    ],
    excludePaths: NOT_DOCS,
    maxEvidence: 6,
  }),
  defineSignal({
    id: 'ai.provider.openweights',
    label: 'Self-hosted or open-weights model',
    category: 'ai-usage',
    description: 'Loads model weights locally (Hugging Face, Ollama, llama.cpp, vLLM).',
    keywords: ['transformers', 'huggingface', 'ollama', 'llama_cpp', 'llama-cpp', 'vllm', 'from_pretrained', 'safetensors'],
    patterns: [
      /from\s+transformers\s+import|AutoModel\w*|AutoTokenizer|from_pretrained\(/,
      /huggingface_hub|hf_hub_download|@huggingface\/\w+/i,
      /\bollama\b.*\b(chat|generate|pull)\b|localhost:11434/i,
      /\bvllm\b|LLM\(model=|llama_cpp|llama\.cpp/i,
    ],
    excludePaths: NOT_DOCS,
    maxEvidence: 6,
  }),
  defineSignal({
    id: 'ai.inference.call',
    label: 'Model inference call site',
    category: 'ai-usage',
    description: 'A place in the code where a model is asked to produce an output.',
    keywords: [
      'chat.completions', 'messages.create', 'generatecontent', 'generate_content',
      '.predict(', 'generatetext', 'streamtext', 'generateobject', 'invoke(', '.forward(',
    ],
    patterns: [
      /\.(chat\.completions|completions)\.create\s*\(/,
      /\.messages\.create\s*\(/,
      /generate(Content|Text|Object|Stream)\s*\(|generate_content\s*\(/,
      /\.(predict|predict_proba|infer|forward)\s*\(/,
      /\b(streamText|generateText|generateObject|streamObject)\s*\(/,
      /\bmodel\.invoke\s*\(|\bchain\.(invoke|run)\s*\(/,
    ],
    excludePaths: NOT_DOCS,
    scope: 'code',
    maxEvidence: 10,
  }),
  defineSignal({
    id: 'ai.framework.agent',
    label: 'Agent / orchestration framework',
    category: 'ai-usage',
    description: 'Uses an agent framework that lets a model take actions autonomously.',
    keywords: ['langchain', 'llamaindex', 'llama_index', 'langgraph', 'crewai', 'autogen', 'semantic-kernel', 'haystack', 'ai-sdk', 'agents'],
    patterns: [
      /from\s+langchain|require\(['"]langchain|@langchain\//i,
      /llama_index|llamaindex|@llamaindex\//i,
      /langgraph|crewai|autogen|semantic_kernel|semantic-kernel|haystack/i,
      /\b(AgentExecutor|create_react_agent|StateGraph|Crew\()/,
    ],
    excludePaths: NOT_DOCS,
    maxEvidence: 6,
  }),
  defineSignal({
    id: 'ai.ml.classical',
    label: 'Classical ML / statistical model',
    category: 'ai-usage',
    description: 'Trains or serves a classical ML model (scikit-learn, XGBoost, PyTorch, TensorFlow).',
    keywords: [
      'sklearn', 'scikit-learn', 'xgboost', 'lightgbm', 'torch', 'tensorflow', 'keras', 'catboost',
      'statsmodels', 'opencv', 'deepface', 'face_recognition', 'insightface', 'facenet', 'mediapipe',
      // Class names that appear without their import ; a model loaded from a
      // pickle, or a notebook cell run after the imports scrolled away.
      'randomforest', 'logisticregression', 'gradientboosting', 'xgbclassifier',
      'lgbmclassifier', 'nn.module',
    ],
    patterns: [
      /from\s+sklearn|import\s+sklearn|from\s+xgboost|import\s+xgboost|import\s+lightgbm/,
      /import\s+torch\b|from\s+torch\b|import\s+tensorflow|from\s+tensorflow|from\s+keras/,
      /\b(RandomForest|LogisticRegression|GradientBoosting|XGBClassifier|LGBMClassifier|nn\.Module)\b/,
      // Computer-vision and biometric model libraries are AI systems too.
      /\b(import|from|require)\b[^\n]{0,30}\b(cv2|opencv|deepface|face_recognition|insightface|facenet|mediapipe|dlib)\b/i,
    ],
    excludePaths: NOT_DOCS,
    maxEvidence: 6,
  }),
  defineSignal({
    id: 'ai.ml.training',
    label: 'Model training in-repo',
    category: 'ai-usage',
    description: 'The repository trains or fine-tunes a model, not just calls one.',
    keywords: ['.fit(', 'train_test_split', 'trainer(', 'fine_tune', 'finetune', 'fine_tuning', 'train_loop', 'optimizer', 'epochs'],
    patterns: [
      /\.fit\s*\(\s*[XxTt]|train_test_split\s*\(|\bTrainer\s*\(/,
      /\b(fine[_-]?tun\w+)\b/i,
      /for\s+epoch\s+in\s+range|optimizer\.step\(\)|loss\.backward\(\)/,
      /\bcreate_fine_tuning_job\b|\bfine_tuning\.jobs\b/,
    ],
    excludePaths: NOT_DOCS,
    scope: 'code',
    maxEvidence: 6,
  }),
  defineSignal({
    id: 'ai.rag.retrieval',
    label: 'Retrieval-augmented generation',
    category: 'ai-usage',
    description: 'Embeds documents and retrieves them to ground model output.',
    keywords: ['embedding', 'pinecone', 'weaviate', 'qdrant', 'chroma', 'pgvector', 'faiss', 'similarity_search', 'vectorstore'],
    patterns: [
      /embeddings?\.(create|embed|embed_query|embedDocuments)/i,
      /\b(pinecone|weaviate|qdrant|chromadb|chroma|faiss|pgvector|milvus)\b/i,
      /similarity_search|vector(_|-)?(store|search|index)|cosine_similarity/i,
    ],
    excludePaths: NOT_DOCS,
    maxEvidence: 6,
  }),
  defineSignal({
    id: 'ai.prompt.system',
    label: 'System prompt / prompt template',
    category: 'ai-usage',
    description: 'Defines the instructions that shape model behaviour ; a core design choice under Art. 11.',
    keywords: ['system prompt', 'system_prompt', 'systemprompt', 'role": "system', "role': 'system", 'prompttemplate', 'prompt_template'],
    patterns: [
      /\b(SYSTEM_PROMPT|system_prompt|systemPrompt|SYSTEM_MESSAGE)\b/,
      /['"]role['"]\s*:\s*['"]system['"]/,
      /PromptTemplate|ChatPromptTemplate|prompt_template/i,
      /\bsystem\s*:\s*[`'"]/,
    ],
    excludePaths: NOT_DOCS,
    scope: 'code',
    maxEvidence: 8,
  }),
  defineSignal({
    id: 'ai.autonomy.tooluse',
    label: 'Model-invoked tool or function calling',
    category: 'ai-usage',
    description: 'The model can trigger side effects ; raises the human-oversight bar under Art. 14.',
    keywords: ['tool_calls', 'toolcalls', 'function_call', 'tool_use', 'tools=[', 'tools: [', 'tool_choice'],
    patterns: [
      /\btool_calls?\b|\btoolCalls?\b|\bfunction_call\b|\btool_use\b/,
      /\btools\s*[:=]\s*\[/,
      /\btool_choice\b|\bexecute_tool\b|\bdispatchTool\b/,
    ],
    excludePaths: NOT_DOCS,
    scope: 'code',
    maxEvidence: 6,
  }),
];
