/**
 * Regenerate every artefact that is checked in but derived from the engine.
 *
 * Usage: node scripts/artefacts.mjs
 *
 * These files — the example dossier, the standards exports, the deck PDF and
 * its slide stills — are committed so a reader can open them without running
 * anything. That makes them a drift hazard: every time a control is added or a
 * citation is corrected, the committed copy becomes a claim the code no longer
 * supports. Regenerating them is therefore a single command, run at the end of
 * every change to the corpus.
 */
import { execFileSync } from 'node:child_process';
import { cpSync } from 'node:fs';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { chromium } from 'playwright';

const ROOT = resolve(import.meta.dirname, '..');
const CLI = resolve(ROOT, 'packages/cli/dist/bin.js');
/** The failing tree, for the artefact whose job is to carry findings. */
const FIXTURE = 'fixtures/hireflow';
/** The remediated tree — "HireFlow v3" in the demo — for the artefacts a
 *  customer is actually handed: an attestation and a model inventory. */
const REMEDIATED = 'fixtures/hireflow-remediated';

/** The deck slides reproduced as stills in the write-up. */
const DECK_STILLS = [1, 3, 5, 6, 7, 8];

const run = (args) => {
  execFileSync(process.execPath, [CLI, ...args], { cwd: ROOT, stdio: ['ignore', 'ignore', 'inherit'] });
  process.stdout.write(`  ✔ ${args.join(' ')}\n`);
};

process.stdout.write('\nStandards exports and the example dossier\n');
await mkdir(resolve(ROOT, 'docs/examples'), { recursive: true });
run(['scan', FIXTURE, '--format', 'sarif', '--out', 'docs/examples/hireflow.sarif', '--quiet']);
run(['scan', REMEDIATED, '--format', 'cdxa', '--out', 'docs/examples/hireflow-v3-attestation.cdx.json', '--quiet']);
run(['scan', REMEDIATED, '--format', 'mlbom', '--out', 'docs/examples/hireflow-v3.mlbom.cdx.json', '--quiet']);
run(['dossier', FIXTURE, '--html', '--out', '/tmp/annex-dossier.html']);

const browser = await chromium
  .launch({ executablePath: process.env.PLAYWRIGHT_CHROMIUM || '/opt/pw-browsers/chromium' })
  .catch(() => chromium.launch());

const pdf = async (input, output, landscape) => {
  const page = await browser.newPage({ viewport: { width: 1440, height: 810 } });
  await page.goto(`file://${resolve(input)}`, { waitUntil: 'networkidle' });
  await page.emulateMedia({ media: 'print' });
  await page.pdf({
    path: resolve(ROOT, output),
    format: 'A4',
    landscape,
    printBackground: true,
    ...(landscape ? {} : { margin: { top: '18mm', bottom: '18mm', left: '16mm', right: '16mm' } }),
  });
  await page.close();
  process.stdout.write(`  ✔ ${output}\n`);
};

/**
 * The landing page's terminal block.
 *
 * It used to be hand-typeset JSX under a comment insisting it was verbatim,
 * and it had drifted from the real output in six places including the ledger
 * fingerprint. A product whose argument is that documents people write about
 * themselves are worthless cannot open with a mock-up of its own output, so
 * the block is now captured from the CLI and regenerated here.
 */
process.stdout.write('\nLanding-page capture\n');
const HERO_ARGS = ['scan', FIXTURE, '--markets', 'eu,us-nyc', '--turnover', '9800000', '--employees', '40', '--quiet'];
const heroRaw = execFileSync(process.execPath, [CLI, ...HERO_ARGS], { cwd: ROOT, encoding: 'utf8' });
// eslint-disable-next-line no-control-regex
const hero = heroRaw.replace(/\u001b\[[0-9;]*m/g, '').split('\n');
const gapCount = hero.filter((l) => /^\s{4}[✖▲]\s+(missing|partial|review)/.test(l)).length;
const classificationEnd = hero.findIndex((l) => l.startsWith('Gaps'));
const shown = [...hero.slice(0, 22), ...hero.slice(classificationEnd, classificationEnd + 6)]
  .join('\n')
  .replace(/\n{3,}/g, '\n\n')
  .trim();
const heroFile = 'apps/web/src/app/hero-capture.ts';
await writeFile(
  resolve(ROOT, heroFile),
  `// Generated by scripts/artefacts.mjs. Do not edit: this is literal CLI\n` +
    `// output, and hand-editing it is the exact failure it exists to prevent.\n` +
    `export const HERO_COMMAND = ${JSON.stringify(`annex ${HERO_ARGS.slice(0, -1).join(' ').replace(FIXTURE, '.')}`)};\n` +
    `export const HERO_GAP_COUNT = ${gapCount};\n` +
    `export const HERO_OUTPUT = ${JSON.stringify(shown)};\n`,
  'utf8',
);
process.stdout.write(`  ✔ ${heroFile} (${gapCount} gaps in the full run)\n`);

/**
 * The README's terminal transcripts, captured rather than typed.
 *
 * The landing page's block had already been moved here, and the README's had
 * not — so it went stale in six places while promising, in the paragraph
 * underneath it, that "every line shown is verbatim". A judge ran the command
 * and found a different ledger fingerprint, two different scores and a
 * different gap count. The machinery existed; it was pointed at one file.
 *
 * Each capture names the command it runs and what it keeps, because a
 * transcript trimmed to fit is honest only if the trimming is by whole lines.
 */
process.stdout.write('\nREADME transcripts\n');

const strip = (out) => out.replace(/\u001b\[[0-9;]*m/g, '');
const capture = (args, opts = {}) =>
  strip(execFileSync(process.execPath, [CLI, ...args], { cwd: ROOT, encoding: 'utf8', ...opts }));
// `diff` and `verify` exit non-zero by design when they find something, which
// is the case the README is showing.
const captureAllowingFailure = (args) => {
  try {
    return capture(args);
  } catch (err) {
    return strip(String(err.stdout ?? ''));
  }
};

const KEYDIR = resolve(ROOT, 'node_modules/.cache/annex-readme');
await mkdir(KEYDIR, { recursive: true });
execFileSync(process.execPath, [CLI, 'keygen', '--out', KEYDIR], { cwd: ROOT, stdio: 'ignore' });

const captures = {};

// 1. The hero scan: the header, two findings, three gaps.
{
  const full = capture(['scan', FIXTURE, '--markets', 'eu,us-nyc', '--turnover', '9800000', '--employees', '40', '--quiet']).split('\n');
  const gapCount = full.filter((l) => /^\s{4}[✖▲]\s+(missing|partial|review)/.test(l)).length;
  const classificationAt = full.findIndex((l) => l.startsWith('Classification'));
  const gapsAt = full.findIndex((l) => l.startsWith('Gaps'));
  const firstGap = full.findIndex((l, i) => i > gapsAt && /^\s{4}✖ missing/.test(l));
  captures.hero = [
    '$ annex scan fixtures/hireflow --markets eu,us-nyc --turnover 9800000 --employees 40',
    // Through the second finding's citation and its first evidence line — the
    // prose under the block in the README points at that line by name.
    ...full.slice(0, classificationAt + 11),
    '',
    ...full.slice(gapsAt, gapsAt + 2),
    '',
    ...full.slice(firstGap, firstGap + 12),
  ].join('\n').replace(/\n{3,}/g, '\n\n');
  captures.heroGapCount = String(gapCount);
}

// 2. `fix --write` then rescan, showing two capped controls.
{
  const tmp = resolve(ROOT, 'node_modules/.cache/annex-readme-fix');
  await rm(tmp, { recursive: true, force: true });
  cpSync(resolve(ROOT, 'fixtures/lendwise'), tmp, { recursive: true });
  const before = capture(['scan', tmp, '--format', 'json', '--quiet']);
  execFileSync(process.execPath, [CLI, 'fix', tmp, '--write'], { cwd: ROOT, stdio: 'ignore' });
  const after = capture(['scan', tmp, '--quiet', '--all']).split('\n');
  const pick = (title) => {
    const at = after.findIndex((l) => l.includes(title));
    return at === -1 ? [] : after.slice(at, at + 8);
  };
  captures.fix = [
    '$ annex fix . --write && annex scan . --all',
    '',
    ...pick('Effective human oversight'),
    '',
    ...pick('Risk management system'),
  ].join('\n');
  captures.fixBefore = String(JSON.parse(before).score);
  captures.fixAfter = String(JSON.parse(capture(['scan', tmp, '--format', 'json', '--quiet'])).score);
  await rm(tmp, { recursive: true, force: true });
}

// 3 and 4. Verify, unsigned and signed, plus the tampered case.
{
  const report = resolve(ROOT, 'node_modules/.cache/annex-readme/report.json');
  capture(['scan', FIXTURE, '--format', 'json', '--out', report, '--quiet']);
  captures.verify = ['$ annex verify report.json --against fixtures/hireflow', capture(['verify', report, '--against', FIXTURE])].join('\n');

  const signed = resolve(ROOT, 'node_modules/.cache/annex-readme/signed.json');
  capture(['scan', FIXTURE, '--format', 'json', '--out', signed, '--sign', resolve(KEYDIR, 'annex-signing.key'), '--quiet']);
  captures.sign = [
    '$ annex keygen',
    '$ annex scan . --format json --out report.json --sign annex-signing.key',
    '$ annex verify report.json --pubkey annex-signing.pub',
    captureAllowingFailure(['verify', signed, '--pubkey', resolve(KEYDIR, 'annex-signing.pub')]).split('\n').slice(0, 8).join('\n'),
  ].join('\n');
}

// 5. The substantial-modification diff.
{
  captures.diff = [
    '$ annex diff --base fixtures/hireflow-remediated --head fixtures/hireflow',
    captureAllowingFailure(['diff', '--base', 'fixtures/hireflow-remediated', '--head', 'fixtures/hireflow']),
  ].join('\n');
}

// 6. The five attempts on Article 14. Abridged to the badge and the reason,
//    because the full run is three screens and the README is showing the
//    shape of the answer rather than reproducing the script.
{
  const full = strip(execFileSync(process.execPath, [resolve(ROOT, 'scripts/attack.mjs')], { cwd: ROOT, encoding: 'utf8' }));
  const lines = full.split('\n');
  const kept = [];
  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i] ?? '';
    if (/^\d+\. /.test(line)) {
      kept.push('', line);
      continue;
    }
    if (!/^\s+(SATISFIED|PARTIAL|MISSING)/.test(line)) continue;
    kept.push(line.replace(/\s+$/, ''));
    // The reason, to its first full stop. Cutting at a fixed line count left
    // every entry ending mid-clause, which reads as a broken paste rather
    // than an abridgement.
    const reason = [];
    for (let j = i + 1; j < lines.length && (lines[j] ?? '').trim() && !/^→/.test((lines[j] ?? '').trim()); j += 1) {
      reason.push((lines[j] ?? '').trim());
    }
    const sentence = reason.join(' ').split(/(?<=\.)\s/)[0];
    if (sentence) kept.push(`   ${sentence}`);
    // Steps 3 and 4 fail for the same stated reason — nothing reaches the
    // module — and the difference between them is the whole point, so where
    // the sentence repeats, print the gap clause that distinguishes them.
    if (sentence && kept.filter((l) => l === `   ${sentence}`).length > 1) {
      const gap = lines.slice(i + 1).find((l) => l.trim().startsWith('→'));
      const rest = [];
      if (gap) {
        const at = lines.indexOf(gap);
        for (let j = at; j < lines.length && (lines[j] ?? '').trim(); j += 1) rest.push((lines[j] ?? '').trim());
      }
      const clause = rest.join(' ').replace(/^→\s*/, '').split(': ').slice(1).join(': ');
      if (clause) kept.push(`   → ${clause.split(/(?<=\.)\s/)[0]}`);
    }
  }
  captures.attack = ['$ npm run attack', ...kept].join('\n').replace(/\n{3,}/g, '\n\n').trim();
}

{
  const readmePath = resolve(ROOT, 'README.md');
  let readme = await readFile(readmePath, 'utf8');
  for (const name of ['hero', 'fix', 'verify', 'sign', 'diff', 'attack']) {
    const marker = new RegExp(`(<!-- capture:${name} -->\\n\`\`\`\\n)[\\s\\S]*?(\\n\`\`\`\\n<!-- /capture:${name} -->)`);
    if (!marker.test(readme)) throw new Error(`README has no capture:${name} block`);
    readme = readme.replace(marker, `$1${captures[name].trim()}$2`);
  }
  readme = readme
    .replace(/The real run prints \d+ gaps/, `The real run prints ${captures.heroGapCount} gaps`)
    .replace(/the LendWise fixture moves the score \d+ → \d+/, `the LendWise fixture moves the score ${captures.fixBefore} → ${captures.fixAfter}`);
  await writeFile(readmePath, readme, 'utf8');
  process.stdout.write('  ✔ README.md (6 transcripts, regenerated from the CLI)\n');
}

process.stdout.write('\nPDFs\n');
await pdf('/tmp/annex-dossier.html', 'docs/examples/annex-iv-dossier-hireflow.pdf', false);
await pdf(resolve(ROOT, 'docs/deck/index.html'), 'docs/deck/annex-pitch-deck.pdf', true);

process.stdout.write('\nDeck stills\n');
const page = await browser.newPage({ viewport: { width: 1440, height: 810 }, deviceScaleFactor: 2 });
await page.goto(`file://${resolve(ROOT, 'docs/deck/index.html')}`, { waitUntil: 'networkidle' });
const slides = await page.locator('section.slide').all();

// A slide is a fixed 297x167mm box with `overflow: hidden`, so content that
// does not fit is silently cut off mid-sentence rather than reflowing. That
// happened once and shipped; check every slide instead of eyeballing them.
// The slide is a fixed-height flex column, so a block that does not fit is
// not pushed past the edge — it is squeezed, and its own `overflow: hidden`
// then cuts the text off mid-line. That happened to the diff slide and
// shipped. Check every clipping box for content taller than the box.
const overflowing = await page.$$eval('section.slide', (nodes) => {
  const out = [];
  nodes.forEach((slide, i) => {
    const boxes = [slide, ...slide.querySelectorAll('*')].filter(
      (el) => getComputedStyle(el).overflow !== 'visible',
    );
    for (const el of boxes) {
      const over = Math.round(el.scrollHeight - el.clientHeight);
      if (over > 1) out.push({ n: i + 1, tag: el.tagName.toLowerCase(), over });
    }
  });
  return out;
});
if (overflowing.length > 0) {
  const detail = overflowing.map((s) => `slide ${s.n} clips ${s.over}px inside <${s.tag}>`).join(', ');
  throw new Error(`the deck does not fit its own page size: ${detail}`);
}

for (const n of DECK_STILLS) {
  const slide = slides[n - 1];
  if (!slide) throw new Error(`the deck has no slide ${n} (it has ${slides.length})`);
  const name = `docs/deck/slide-${String(n).padStart(2, '0')}.png`;
  await slide.screenshot({ path: resolve(ROOT, name) });
  process.stdout.write(`  ✔ ${name}\n`);
}

await browser.close();
process.stdout.write('\nAll artefacts regenerated.\n');
